# Generated by Django 3.2 on 2023-06-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220422_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='slug жанра'),
        ),
    ]
